env:
  staging:
    log_level: "DEBUG"

  prod:
    log_level: "INFO"
# log_level takes its value in { DEBUG, INFO, WARN, ERROR, CRITICAL }

log_file: ../logs/app_log.txt
data_dir: ../data/
model_batch_size: 50
max_iterations: 100