version: 2.1
# Define the jobs we want to run for this project
jobs:
  compile:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      # command to build all files
      - run: make build
  test:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: make test


# Orchestrate our job run sequence
workflows:
  version: 2.1
  compile_and_test:
    jobs:
      - compile
      - test:
          requires:
            - compile