version: 2.1
# Define the jobs we want to run for this project
jobs:
  compile:
    docker:
      - image: gcc:10.2
    steps:
      - checkout
      # command to build all files
      - run: apt-get update && apt-get -y install doxygen
      - run: version=3.19; build=1; mkdir ~/temp; cd ~/temp; wget https://cmake.org/files/v$version/cmake-$version.$build-Linux-x86_64.sh ; 
      - run: mkdir /opt/cmake; 
      - run: version=3.19; build=1; sh cmake-$version.$build-Linux-x86_64.sh --prefix=/opt/cmake
      - run: ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
      - run: git submodule init; git submodule update
      - run: mkdir build; cd build; cmake .. -DBUILD_DEPS:BOOL=ON -DUSE_SCIP=OFF; make
      - persist_to_workspace:
          root: ./
          paths: 
            - ./
  test:
    docker:
      - image: gcc:9.3
    steps:
      # instead of checking out, restore workspace (will merge all parallel containers from previous job)
      - attach_workspace:
          at: ./
      - run: cd build; ./Test

  doc_generation:
    docker:
      - image: gcc:9.3
    steps:
      # instead of checking out, restore workspace (will merge all parallel containers from previous job)
      - attach_workspace:
          at: ./
      - run: apt-get update && apt-get -y install cmake && apt-get -y install doxygen
      - run: cd doc; cmake .; doxygen Doxyfile.Doxygen 


# Orchestrate our job run sequence
workflows:
  version: 2.1
  compile_and_test:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - doc_generation:
          requires:
            - compile