version: 2.1
# Define the jobs we want to run for this project
jobs:
  compile:
    docker:
      - image: gcc:9.3
    steps:
      - checkout
      # command to build all files
      - run: apt-get update && apt-get -y install cmake
      - run: git submodule init; git submodule update
      - run: mkdir build; cd build; cmake ..; make
      - persist_to_workspace:
          root: build
          paths: 
            - "."
  test:
    docker:
      - image: gcc:9.3
    steps:
      # instead of checking out, restore workspace (will merge all parallel containers from previous job)
      - attach_workspace:
          at: ~/
      - run: cd build; ./Test


# Orchestrate our job run sequence
workflows:
  version: 2.1
  compile_and_test:
    jobs:
      - compile
      - test:
          requires:
            - compile