version: 2.1
# Define the jobs we want to run for this project
jobs:
  compile:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      # command to build all files
      - run: git submodule init
      - run: git submodule update
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make
      - persist_to_workspace:
          root: ~/
          paths: build
  test:
    docker:
      - image: gcc:8.2
    steps:
      # instead of checking out, restore workspace (will merge all parallel containers from previous job)
      - attach_workspace:
          at: ~/
      - run: cd build
      - run: ./Test


# Orchestrate our job run sequence
workflows:
  version: 2.1
  compile_and_test:
    jobs:
      - compile
      - test:
          requires:
            - compile